# These are supported funding model platforms
custom: ['https://realjournal.github.io/the-truth-behind-social-media/','https://realjournal.github.io/upgrading-your-ps4-game-library-to-playstation-5/','https://realjournal.github.io/when-jokes-become-too-much/','https://realjournal.github.io/why-brunei-missed-its-chance-to-diversify-its-economy/','https://realjournal.github.io/yoga-for-all-levels-a-complete-guide-to-practice-yoga-twice-a-day-safely/']

