name = "benmanns"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20.11.1"
POSTHOG_PROJECT_API_KEY="phc_K3cjgnQyImv3S9EJ7GuhDRj56Wtc89ZUVehTdx5KJQJ"
