name: Article Status Management

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  manage-article-status:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'content')
    steps:
      - name: Check Issue Labels
        id: check_labels
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const hasInProgress = issue.labels.some(label => label.name === 'in-progress');
            const hasReview = issue.labels.some(label => label.name === 'review');

            // 如果是新建的文章 issue，自动添加 in-progress 标签
            if (context.payload.action === 'opened') {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['in-progress']
              });
              return;
            }

            // 如果同时有 in-progress 和 review 标签，移除 in-progress
            if (hasInProgress && hasReview) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: 'in-progress'
              });
            }

            // 如果既没有 in-progress 也没有 review 标签，添加 in-progress
            if (!hasInProgress && !hasReview) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['in-progress']
              });
            }
